PYTHON = python

.PHONY: help install_env install pgfn-data start stop clean clean_all clean_env
.DEFAULT_GOAL := help

help:
	@echo "Makefile para o projeto Dask"
	@echo "Comandos disponíveis:"
	@echo "  install       - cria/atualiza o ambiente e instala os requisitos"
	@echo "  start         - inicia o container Docker"
	@echo "  stop          - para o container Docker"
	@echo "  clean         - remove o container Docker"
	@echo "  clean_all     - remove o container e a imagem Docker"
	@echo "  clean_env     - remove o ambiente virtual Python"
	@echo "  pgfn-data     - baixa os dados da PGFN"

install_env:clean_env
	@echo "🔧 Criando ambiente virtual em ./venv"
	$(PYTHON) -m venv venv
	@echo "🔧 Atualizando pip"
	@venv/bin/python -m pip install --upgrade pip > /dev/null || (echo "Erro ao atualizar pip" && exit 1)
	@echo "🔧 Instalando dependências do requirements.txt"
	@venv/bin/python -m pip install -r requirements.txt > /dev/null || (echo "Erro ao instalar dependências" && exit 1)
	@echo "✅ Ambiente virtual criado e dependências instaladas"

install: install_env
	@echo "📁 Criando diretórios padrão do projeto..."
	@mkdir -p data/{sample,raw,interim,external,processed}
	@mkdir -p models reports notebooks docs references utils
	@mkdir -p scripts/{config,p01_data,p02_etl,p03_feature_engineering,p04_modeling,p05_evaluation,p06_deployment,p07_monitoring}

	@for dir in config \
				utils \
				p01_data \
				p02_etl \
				p03_feature_engineering \
				p04_modeling \
				p05_evaluation \
				p06_deployment \
				p07_monitoring; do \
		mkdir -p scripts/$$dir; \
	done
	

	@touch scripts/__init__.py
	@touch scripts/config/__init__.py scripts/config/settings.py
	@for dir in config \
				utils \
				p01_data \
				p02_etl \
				p03_feature_engineering \
				p04_modeling \
				p05_evaluation \
				p06_deployment \
				p07_monitoring; do \
		touch scripts/$$dir/__init__.py; \
	done

	@echo "DATA_DIR=$$HOME/Documents/dados" > example.env
	@echo "✅ Projeto inicializado com sucesso!"

pgfn-data:
	@echo "📥 Baixando dados do PGFN (simulado)"
	# venv/bin/python scripts/p01_data/download_pgfn.py

start:
	docker compose -f docker/dask/docker-compose.yml up -d

stop:
	docker compose -f docker/dask/docker-compose.yml down

clean:
	docker compose -f docker/dask/docker-compose.yml rm -f

clean_all:
	docker compose -f docker/dask/docker-compose.yml down --rmi all

clean_env:
	@echo "🧹 Removendo ambiente virtual..."
	@rm -rf venv
	@find . -type d -name "__pycache__" -exec rm -r {} +
